version: "3.3"
# start with docker compose up --build

services:
  backend:
    build: .
    ports:
    - "${PORT:-3000}:3000"
    networks:
    - one-place-network
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-30d}

networks:
  one-place-network: